/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processLogger_lli_LowerLevelInfoFetcher */

#ifndef _Included_processLogger_lli_LowerLevelInfoFetcher
#define _Included_processLogger_lli_LowerLevelInfoFetcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processLogger_lli_LowerLevelInfoFetcher
 * Method:    nativePrint
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_processLogger_lli_LowerLevelInfoFetcher_nativePrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
